Upgrade rails to 5.1.3

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,43 +1,38 @@
-#!/bin/sh
+#!/usr/bin/env ruby
+require 'pathname'
+require 'fileutils'
+include FileUtils
 
-# Set up Rails app. Run this script immediately after cloning the codebase.
-# https://github.com/thoughtbot/guides/tree/master/protocol
+# path to your application root.
+APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
 
-# Exit if any subcommand fails
-set -e
+def system!(*args)
+  system(*args) || abort("\n== Command #{args} failed ==")
+end
 
-# Set up Ruby dependencies via Bundler
-gem install bundler --conservative
-bundle check || bundle install
+chdir APP_ROOT do
+  # This script is a starting point to setup your application.
+  # Add necessary setup steps to this file.
 
-# Set up database and add any development seed data
-bin/rake dev:prime
+  puts '== Installing dependencies =='
+  system! 'gem install bundler --conservative'
+  system('bundle check') || system!('bundle install')
 
-# Add binstubs to PATH via export PATH=".git/safe/../../bin:$PATH" in ~/.zshenv
-mkdir -p .git/safe
-
-# Only if this isn't CI
-# if [ -z "$CI" ]; then
-# fi
-
-if heroku join --app brufer-staging > /dev/null 2>&1; then
-  git remote add staging git@heroku.com:brufer-staging.git || true
-  printf 'You are a collaborator on the "brufer-staging" Heroku app
-'
-else
-  printf 'Ask for access to the "brufer-staging" Heroku app
-'
-fi
+  # Install JavaScript dependencies if using Yarn
+  # system('bin/yarn')
 
 
-if heroku join --app brufer-production > /dev/null 2>&1; then
-  git remote add production git@heroku.com:brufer-production.git || true
-  printf 'You are a collaborator on the "brufer-production" Heroku app
-'
-else
-  printf 'Ask for access to the "brufer-production" Heroku app
-'
-fi
+  # puts "\n== Copying sample files =="
+  # unless File.exist?('config/database.yml')
+  #   cp 'config/database.yml.sample', 'config/database.yml'
+  # end
 
+  puts "\n== Preparing database =="
+  system! 'bin/rails db:setup'
 
-git config heroku.remote staging
+  puts "\n== Removing old logs and tempfiles =="
+  system! 'bin/rails log:clear tmp:clear'
+
+  puts "\n== Restarting application server =="
+  system! 'bin/rails restart'
+end
